### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by agoalofalife**

### CODE REVIEW

**Comment by ptkdev** [comment]
IMHO `camelCase` is bad, i prefer `snake_case`

**Comment by agoalofalife** [comment]
I'm not happy with `snake_case`, but i fixed
I suggest `camelCase` for class names

**Comment by agoalofalife** [comment]
@ptkdev 
not who uses class names `snake_case`
enough to see node.js code native

**Comment by ptkdev** [comment]
You ara right, but snake_case is only development rules in this project. Sorry

**Pull request merged**
